version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "personas-jo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9ewhdph3p3ik"
s3_prefix = "personas-jo"
region = "us-east-1"
profile = "ceci"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Dev\" DbUser=\"\" DbPassword=\"\" DbHost=\"\" Db=\"\" CaptchaKey=\"\" CognitoCustomerUserPool=\"\" CognitoCustomerClientId=\"\""
image_repositories = []
